name: readthedocs/actions

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - draft

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: pet-mad